<a href="https://colab.research.google.com/github/emmanuel1127/PSP/blob/main/Copy_of_NigerianRoadTraffic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Importing excel file

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
file_path = '/Book1NRT.xlsx'
data = pd.read_excel(file_path)

In [ ]:
data.head()

,Quarter,State,Total_Crashes,Num_Injured,Num_Killed,Total_Vehicles_Involved,Speed Violation,Drunk and Driving,Poor Weather,Fatigue,Other_Factors
0,Q4 2020,Abia,30,146,31,37,19,0,0,0,18
1,Q4 2020,Adamawa,77,234,36,94,57,0,0,0,37
2,Q4 2020,Akwa Ibom,22,28,7,24,15,0,0,1,8
3,Q4 2020,Anambra,72,152,20,83,43,1,0,0,39
4,Q4 2020,Bauchi,154,685,90,140,74,0,0,0,66

In [ ]:
data.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
513    False
514    False
515    False
516    False
517    False
Length: 518, dtype: bool

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 518 entries, 0 to 517
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Quarter                  518 non-null    object
 1   State                    518 non-null    object
 2   Total_Crashes            518 non-null    int64
 3   Num_Injured              518 non-null    int64
 4   Num_Killed               518 non-null    int64
 5   Total_Vehicles_Involved  518 non-null    int64
 6   Speed Violation          518 non-null    int64
 7   Drunk and Driving        518 non-null    int64
 8   Poor Weather             518 non-null    int64
 9   Fatigue                  518 non-null    int64
 10  Other_Factors            518 non-null    int64
dtypes: int64(9), object(2)
memory usage: 44.6+ KB

In [ ]:
data.describe()

,Total_Crashes,Num_Injured,Num_Killed,Total_Vehicles_Involved,Speed Violation,Drunk and Driving,Poor Weather,Fatigue,Other_Factors
count,518.000000,518.000000,518.000000,518.000000,518.000000,518.000000,518.000000,518.000000,518.000000
mean,83.517375,245.631274,40.600386,100.667954,37.903475,0.140927,0.355212,23.824324,38.444015
std,77.023061,201.131483,36.858302,108.567113,57.093042,0.454320,1.677385,51.024267,61.983992
min,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-348.000000
25%,30.000000,96.250000,15.000000,32.000000,0.000000,0.000000,0.000000,0.000000,12.000000
50%,58.000000,185.500000,30.000000,64.000000,15.000000,0.000000,0.000000,0.000000,27.000000
75%,107.750000,331.500000,55.750000,134.750000,55.000000,0.000000,0.000000,21.000000,57.000000
max,538.000000,1149.000000,224.000000,864.000000,340.000000,4.000000,25.000000,425.000000,586.000000

In [ ]:
data.groupby('Num_Killed')['Total_Vehicles_Involved'].mean()

Num_Killed
0        9.833333
1        9.400000
2       42.333333
3       21.307692
4       29.500000
          ...
194    130.000000
196    368.000000
197    196.000000
217    299.000000
224    363.000000
Name: Total_Vehicles_Involved, Length: 122, dtype: float64